// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ArenixInstagram.tsx": () => import("../components/mockups/ArenixInstagram.tsx"),
  "./components/mockups/ArenixInstagramPosts.tsx": () => import("../components/mockups/ArenixInstagramPosts.tsx"),
  "./components/mockups/Post1Agendamento.tsx": () => import("../components/mockups/Post1Agendamento.tsx"),
  "./components/mockups/Post2Gestao.tsx": () => import("../components/mockups/Post2Gestao.tsx"),
  "./components/mockups/Post3Torneios.tsx": () => import("../components/mockups/Post3Torneios.tsx")
};
